pull_request_rules:
  - name: Automatic merge
    description: Merge auto PR when all CI checks pass
    conditions:
      - '#approved-reviews-by>=1'
      - check-success = CI
      - check-success = Nix CI
      - check-success = pre-commit.ci
      - or:
          - author = dependabot
          - author = pre-commit-ci
    actions:
      merge:
queue_rules:
  - name: default
    branch_protection_injection_mode: queue
    queue_conditions:
      - and:
          - check-success = CI
          - check-success = nix (ubuntu)
          - check-success = nix (macos)
          - approved-reviews-by = nim65s
          - or:
              - author = pre-commit.ci[bot]
              - author = dependabot[bot]
