queue_rules:
  - name: default
    merge_method: merge
    queue_conditions:
      - and:
          - "check-success = CI"
          - "check-success = nix (ubuntu)"
          - "check-success = nix (macos)"
          - or:
            - approved-reviews-by = nim65s
            - author = nim65s
            - author = pre-commit-ci[bot]
            - author = dependabot[bot]

pull_request_rules:
  - name: Automatic queue
    conditions: []
      - actions:
        queue:
