repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.1
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/pappasam/toml-sort
  rev: v0.23.1
  hooks:
  - id: toml-sort-fix
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
