[dependencies]
clap = {features = ["derive", "env"], version = "4.5.16"}
clap_complete = "4.5.23"
minijinja = {features = ["custom_syntax"], version = "2.1.2"}
octocrab = "0.39.0"
regex = "1.10.6"
serde = {features = ["derive"], version = "1.0.209"}
serde_yml = "0.0.12"
thiserror = "1.0.63"
tokio = {features = ["full"], version = "1.39.3"}

[dev-dependencies]
indoc = "2.0.5"

[package]
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
description = "Automatize your fork"
edition = "2021"
keywords = ["git"]
license = "MIT OR Apache-2.0"
name = "fork-manager"
repository = "https://github.com/nim65s/fork-manager"
version = "0.3.0"

[package.metadata.release]
pre-release-replacements = [
  {file = "CHANGELOG.md", min = 1, replace = "{{version}}", search = "unreleased"},
  {exactly = 1, file = "CHANGELOG.md", replace = "...{{tag_name}}", search = "\\.\\.\\.HEAD"},
  {file = "CHANGELOG.md", min = 1, replace = "{{date}}", search = "ReleaseDate"},
  {exactly = 1, file = "CHANGELOG.md", replace = "<!-- next-header -->\n\n## [unreleased] - ReleaseDate\n", search = "<!-- next-header -->"},
  {exactly = 1, file = "CHANGELOG.md", replace = "<!-- next-url -->\n\n[unreleased]: https://github.com/nim65s/pre-commit-sort/compare/{{tag_name}}...HEAD", search = "<!-- next-url -->"},
  {file = "default.nix", replace = "version = \"{{version}}\";", search = "version = \".*\";"}
]
